/* The following code was generated by JFlex 1.4.3 on 08/04/12 22:05 */

package com.kokakiwi.dev.tenc.core.parser;

import java.io.IOException;

/**
 * Scanner for the C programming language.
 *
 * @author Koka El Kiwi (and some codes by Robert Futrell)
 * @version 0.1
 *
 */

public class TencTokenMaker extends TokenParser {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 4;
  public static final int YYINITIAL = 0;
  public static final int VAR_DECLARE = 6;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\7\1\0\1\10\1\36\22\0\1\10\1\21\1\26"+
    "\1\0\1\37\1\63\1\64\1\16\1\13\1\14\1\40\1\6\1\62"+
    "\1\22\1\34\1\15\1\31\3\24\4\4\2\2\1\36\1\66\1\17"+
    "\1\12\1\20\1\11\1\0\4\3\1\5\1\3\5\1\1\33\10\1"+
    "\1\32\2\1\1\25\2\1\1\60\1\23\1\61\1\36\1\1\1\0"+
    "\1\46\1\30\1\44\1\51\1\54\1\35\1\1\1\45\1\41\2\1"+
    "\1\53\1\1\1\42\1\50\2\1\1\47\1\1\1\43\1\55\1\27"+
    "\1\52\1\25\2\1\1\56\1\65\1\57\1\36\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\11\1\2"+
    "\1\3\1\1\1\15\5\2\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\2\1\1\24\3\1\1\25\1\26\1\1"+
    "\2\3\1\1\1\27\1\30\1\31\4\11\1\32\1\33"+
    "\2\11\1\34\1\2\1\1\1\35\5\2\1\36\1\37"+
    "\1\3\1\0\1\3\1\1\1\11\1\40\7\11\1\2"+
    "\1\41\1\42\4\2\1\0\2\11\2\41\1\43\2\2"+
    "\1\41\1\2\1\44\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\245"+
    "\0\245\0\u0181\0\u01b8\0\245\0\245\0\u01ef\0\u0226\0\u025d"+
    "\0\u0294\0\245\0\u02cb\0\u0302\0\u0339\0\u0370\0\245\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\245\0\245\0\245\0\245"+
    "\0\245\0\245\0\u04ba\0\u04f1\0\245\0\u0528\0\u055f\0\u0596"+
    "\0\245\0\245\0\u05cd\0\u0604\0\u063b\0\u0672\0\245\0\245"+
    "\0\245\0\u06a9\0\u06e0\0\245\0\u0717\0\245\0\245\0\u074e"+
    "\0\u0785\0\245\0\u07bc\0\u07f3\0\u0113\0\u082a\0\u0861\0\u0898"+
    "\0\u08cf\0\u0906\0\245\0\245\0\u093d\0\u0974\0\334\0\u09ab"+
    "\0\u09e2\0\245\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c"+
    "\0\u0b63\0\u0b9a\0\u0bd1\0\u0113\0\u0c08\0\u0c3f\0\u0c76\0\u0cad"+
    "\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0113\0\u0df7\0\u0e2e"+
    "\0\334\0\u0e65\0\u0113\0\u0113";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\6\1\7\1\6\1\10\1\11"+
    "\1\12\1\11\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\11\1\22\1\5\1\7\1\6\1\23\1\24"+
    "\1\6\1\25\2\6\1\26\1\6\1\11\1\5\1\27"+
    "\1\30\1\31\1\6\1\32\2\6\1\33\2\6\1\34"+
    "\3\6\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\7\46\1\11\25\46\1\11\2\46\1\47"+
    "\4\46\1\11\4\46\1\11\14\46\7\50\1\51\25\50"+
    "\1\11\7\50\1\11\4\50\1\11\14\50\67\0\6\5"+
    "\15\0\3\5\1\0\5\5\1\0\1\5\1\0\1\5"+
    "\1\0\15\5\11\0\1\5\5\6\15\0\1\5\2\6"+
    "\1\0\5\6\1\0\1\6\1\0\1\6\1\52\15\6"+
    "\11\0\2\5\1\7\1\5\1\7\1\53\15\0\1\5"+
    "\1\7\1\5\1\0\2\5\1\7\1\54\1\55\1\56"+
    "\1\5\1\0\1\5\1\0\12\5\1\55\1\53\1\54"+
    "\21\0\1\12\70\0\1\57\71\0\1\60\22\0\1\61"+
    "\26\0\7\62\1\0\1\62\1\63\4\62\1\64\4\62"+
    "\1\65\43\62\12\0\1\66\66\0\1\67\54\0\7\23"+
    "\1\70\13\23\1\71\2\23\1\72\40\23\1\5\5\6"+
    "\15\0\1\5\2\6\1\0\5\6\1\0\1\6\1\0"+
    "\1\6\1\52\7\6\1\73\5\6\11\0\2\5\1\7"+
    "\1\5\1\7\1\53\15\0\1\5\1\7\1\74\1\0"+
    "\2\5\1\7\1\54\1\55\1\56\1\5\1\0\1\5"+
    "\1\0\12\5\1\55\1\53\1\54\13\0\1\56\1\0"+
    "\1\56\17\0\1\56\4\0\1\56\35\0\1\5\5\6"+
    "\15\0\1\5\2\6\1\0\5\6\1\0\1\75\1\0"+
    "\1\6\1\52\1\6\1\76\13\6\11\0\1\5\5\6"+
    "\15\0\1\5\2\6\1\0\5\6\1\0\1\6\1\0"+
    "\1\6\1\52\14\6\1\77\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\4\6\1\100\10\6\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\13\6\1\101\1\6\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\4\6\1\102\10\6\75\0\1\103\67\0\1\104"+
    "\1\0\7\46\1\0\25\46\1\0\2\46\1\0\4\46"+
    "\1\0\4\46\1\0\14\46\15\0\1\51\51\0\7\50"+
    "\1\0\25\50\1\0\7\50\1\0\4\50\1\0\14\50"+
    "\2\5\1\105\1\5\1\105\1\5\1\106\13\0\1\106"+
    "\1\5\1\105\1\5\1\0\2\5\1\105\2\5\1\0"+
    "\1\5\1\0\1\5\1\0\15\5\11\0\6\5\15\0"+
    "\3\5\1\0\4\5\1\107\1\0\1\5\1\0\1\5"+
    "\1\0\12\5\1\107\2\5\11\0\6\5\15\0\3\5"+
    "\1\0\3\5\1\107\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\14\5\1\107\11\0\2\5\1\56\1\5\1\56"+
    "\1\110\15\0\1\5\1\56\1\5\1\0\2\5\1\56"+
    "\2\5\1\0\1\5\1\0\1\5\1\0\13\5\1\110"+
    "\1\5\11\0\7\111\1\0\6\111\1\112\57\111\1\0"+
    "\1\111\1\113\4\111\1\112\54\111\1\114\2\111\1\0"+
    "\1\111\1\62\4\111\1\115\4\111\1\62\1\116\1\117"+
    "\3\62\1\116\3\111\1\62\4\111\2\62\2\111\2\62"+
    "\17\111\23\70\1\120\2\70\1\64\44\70\1\23\2\70"+
    "\1\0\1\70\1\23\4\70\1\23\4\70\2\23\1\121"+
    "\4\23\3\70\1\23\4\70\2\23\2\70\2\23\17\70"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\1\122\14\6\11\0\2\5"+
    "\4\123\15\0\1\5\1\123\1\5\1\0\1\5\2\123"+
    "\2\5\1\0\1\123\1\0\1\5\1\0\3\5\1\123"+
    "\1\5\1\123\2\5\1\123\2\5\1\123\1\5\11\0"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\2\6\1\124\12\6\11\0"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\12\6\1\125\2\6\11\0"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\5\6\1\126\7\6\11\0"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\2\6\1\127\12\6\11\0"+
    "\1\5\5\6\15\0\1\5\2\6\1\0\5\6\1\0"+
    "\1\6\1\0\1\6\1\52\1\130\14\6\11\0\2\5"+
    "\1\105\1\5\1\105\1\5\15\0\1\5\1\105\1\5"+
    "\1\0\2\5\1\105\1\54\1\55\1\0\1\5\1\0"+
    "\1\5\1\0\12\5\1\55\1\5\1\54\13\0\1\105"+
    "\1\0\1\105\17\0\1\105\4\0\1\105\35\0\6\5"+
    "\1\131\13\0\1\131\3\5\1\0\5\5\1\0\1\5"+
    "\1\0\1\5\1\0\15\5\11\0\7\111\1\0\6\111"+
    "\1\64\57\111\1\0\2\111\4\62\1\115\4\62\50\111"+
    "\1\62\2\111\1\0\6\111\1\112\5\111\1\62\4\111"+
    "\1\62\35\111\16\0\1\112\50\0\4\111\1\114\2\111"+
    "\1\0\6\111\1\112\5\111\1\114\4\111\1\114\37\111"+
    "\4\132\1\111\1\0\6\111\1\64\5\111\1\132\3\111"+
    "\2\132\3\111\1\132\6\111\1\132\1\111\1\132\2\111"+
    "\1\132\2\111\1\132\12\111\7\70\1\0\61\70\4\133"+
    "\15\70\1\120\1\133\1\70\1\64\1\70\2\133\3\70"+
    "\1\133\6\70\1\133\1\70\1\133\2\70\1\133\2\70"+
    "\1\133\12\70\1\5\5\6\15\0\1\5\2\6\1\0"+
    "\5\6\1\0\1\6\1\0\1\6\1\52\10\6\1\124"+
    "\4\6\11\0\2\5\4\123\15\0\1\5\1\123\1\5"+
    "\1\0\1\5\2\123\1\134\1\135\1\0\1\123\1\0"+
    "\1\5\1\0\3\5\1\123\1\5\1\123\2\5\1\123"+
    "\1\5\1\135\1\123\1\134\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\12\6\1\136\2\6\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\6\6\1\124\6\6\11\0\1\5\5\6\15\0"+
    "\1\5\2\6\1\0\5\6\1\0\1\6\1\0\1\6"+
    "\1\52\14\6\1\137\11\0\1\5\5\6\15\0\1\5"+
    "\2\6\1\0\5\6\1\0\1\6\1\0\1\6\1\52"+
    "\12\6\1\140\2\6\13\0\1\5\1\0\1\5\17\0"+
    "\1\5\4\0\1\5\35\0\2\111\4\62\1\111\1\0"+
    "\6\111\1\64\5\111\1\62\3\111\2\62\3\111\1\62"+
    "\6\111\1\62\1\111\1\62\2\111\1\62\2\111\1\62"+
    "\12\111\2\70\4\23\15\70\1\120\1\23\1\70\1\64"+
    "\1\70\2\23\3\70\1\23\6\70\1\23\1\70\1\23"+
    "\2\70\1\23\2\70\1\23\12\70\6\5\15\0\3\5"+
    "\1\0\4\5\1\141\1\0\1\5\1\0\1\5\1\0"+
    "\12\5\1\141\2\5\11\0\6\5\15\0\3\5\1\0"+
    "\3\5\1\141\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\14\5\1\141\11\0\1\5\5\6\15\0\1\5\2\6"+
    "\1\0\5\6\1\0\1\6\1\0\1\6\1\52\6\6"+
    "\1\142\6\6\11\0\1\5\5\6\15\0\1\5\2\6"+
    "\1\0\5\6\1\0\1\6\1\0\1\6\1\52\13\6"+
    "\1\143\1\6\11\0\1\5\5\6\15\0\1\5\2\6"+
    "\1\0\5\6\1\0\1\6\1\0\1\6\1\52\1\6"+
    "\1\144\13\6\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3740];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\10\3\1\2\11\2\1\2\11\4\1\1\11"+
    "\4\1\1\11\5\1\6\11\2\1\1\11\3\1\2\11"+
    "\4\1\3\11\2\1\1\11\1\1\2\11\2\1\1\11"+
    "\10\1\2\11\1\1\1\0\3\1\1\11\16\1\1\0"+
    "\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public int parse() throws IOException
    {
        return yylex();
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TencTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public TencTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { addToken(Token.IDENTIFIER);
          }
        case 38: break;
        case 34: 
          { addToken(Token.DATA_TYPE_NAME);
          }
        case 39: break;
        case 26: 
          { addToken(Token.LESSEQ);
          }
        case 40: break;
        case 19: 
          { addToken(Token.MOD);
          }
        case 41: break;
        case 20: 
          { addToken(Token.SEMICOLON);
          }
        case 42: break;
        case 5: 
          { addToken(Token.ASSIGN);
          }
        case 43: break;
        case 25: 
          { yybegin(MLC);
          }
        case 44: break;
        case 29: 
          { addToken(Token.IF);
          }
        case 45: break;
        case 37: 
          { addToken(Token.RETURN);
          }
        case 46: break;
        case 35: 
          { addToken(Token.NULL);
          }
        case 47: break;
        case 11: 
          { addToken(Token.GREATER);
          }
        case 48: break;
        case 31: 
          { addToken(Token.OR);
          }
        case 49: break;
        case 27: 
          { addToken(Token.GREATEREQ);
          }
        case 50: break;
        case 21: 
          { yybegin(YYINITIAL);
          }
        case 51: break;
        case 33: 
          { addToken(Token.DATA_HEX);
          }
        case 52: break;
        case 24: 
          { yybegin(EOL_COMMENT);
          }
        case 53: break;
        case 16: 
          { addToken(Token.OPEN_SQUARE);
          }
        case 54: break;
        case 3: 
          { addToken(Token.DATA_INTEGER);
          }
        case 55: break;
        case 13: 
          { addToken(Token.TIMES);
          }
        case 56: break;
        case 10: 
          { addToken(Token.LESSTHAN);
          }
        case 57: break;
        case 4: 
          { addToken(Token.PLUS);
          }
        case 58: break;
        case 36: 
          { addToken(Token.WHILE);
          }
        case 59: break;
        case 23: 
          { addToken(Token.EQUAL);
          }
        case 60: break;
        case 15: 
          { addToken(Token.CLOSE_BRACK);
          }
        case 61: break;
        case 17: 
          { addToken(Token.CLOSE_SQUARE);
          }
        case 62: break;
        case 14: 
          { addToken(Token.OPEN_BRACK);
          }
        case 63: break;
        case 8: 
          { addToken(Token.DIVIDE);
          }
        case 64: break;
        case 7: 
          { addToken(Token.CLOSE_PAREN);
          }
        case 65: break;
        case 6: 
          { addToken(Token.OPEN_PAREN);
          }
        case 66: break;
        case 12: 
          { addToken(Token.MINUS);
          }
        case 67: break;
        case 32: 
          { addToken(Token.DATA_CHAR);
          }
        case 68: break;
        case 9: 
          { addToken(Token.UNKNOWN);
          }
        case 69: break;
        case 28: 
          { addToken(Token.DATA_STRING);
          }
        case 70: break;
        case 22: 
          { addToken(Token.POINTER_IDENTIFIER);
          }
        case 71: break;
        case 18: 
          { addToken(Token.COMMA);
          }
        case 72: break;
        case 30: 
          { addToken(Token.AND);
          }
        case 73: break;
        case 1: 
          { 
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              return YYEOF;
            }
            case 101: break;
            case YYINITIAL: {
              return YYEOF;
            }
            case 102: break;
            case MLC: {
              return YYEOF;
            }
            case 103: break;
            default:
            return YYEOF;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
